# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0004_auto_20180618_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelop',
            name='envelop_template',
            field=models.FileField(upload_to='', verbose_name='Шаблон конверта'),
        ),
    ]
