# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0005_auto_20191128_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип секретности')),
            ],
            options={
                'verbose_name': 'Тип секретности',
                'verbose_name_plural': 'Типы секретности',
                'ordering': ['name'],
            },
        ),
    ]
