# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0006_secrettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrettype',
            name='short_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='Сокращенное название'),
        ),
    ]
