# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0007_secrettype_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrettype',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
