# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0008_secrettype_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secrettype',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отображаемое название'),
        ),
        migrations.AlterField(
            model_name='secrettype',
            name='short_name',
            field=models.CharField(max_length=15, verbose_name='Сокращенное название'),
        ),
    ]
