# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0009_auto_20191203_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название РПО')),
                ('short_name', models.CharField(max_length=15, verbose_name='Краткое название')),
            ],
            options={
                'verbose_name': 'Вид РПО',
                'verbose_name_plural': 'Виды РПО',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SentEnvelop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата и время создания')),
            ],
        ),
        migrations.AlterModelOptions(
            name='secrettype',
            options={'ordering': ['short_name'], 'verbose_name': 'Тип секретности', 'verbose_name_plural': 'Типы секретности'},
        ),
        migrations.AddField(
            model_name='recepient',
            name='sender',
            field=models.BooleanField(default=False, verbose_name='Признак отправителя'),
        ),
    ]
