# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0011_auto_20191204_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpotype',
            name='short_name',
            field=models.CharField(max_length=25, verbose_name='Краткое название'),
        ),
    ]
