# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0013_auto_20191204_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Envelop_format',
            new_name='EnvelopFormat',
        ),
    ]
