# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-06 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0015_auto_20191204_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('type', models.CharField(choices=[('1', 'МО РФ'), ('2', 'МО РФ'), ('3', 'ГФС иное'), ('4', 'ГФС москва'), ('5', 'почта ФПС'), ('6', 'почта России'), ('7', 'посылки')], max_length=20, verbose_name='Тип реестра')),
                ('rpo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.RPOType')),
            ],
            options={
                'verbose_name': 'Реестр',
                'verbose_name_plural': 'Реестры',
                'ordering': ['-pk'],
            },
        ),
    ]
