# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-06 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0016_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenvelop',
            name='registry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.Registry'),
        ),
    ]
