# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-07 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0018_auto_20191206_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='rpo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.RPOType', verbose_name='Тип РПО'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='type',
            field=models.CharField(choices=[('1', 'МО РФ'), ('2', 'МО РФ'), ('3', 'ГФС иное'), ('4', 'ГФС москва'), ('5', 'почта ФПС'), ('6', 'почта России'), ('7', 'посылки')], default='1', max_length=20, verbose_name='Тип реестра'),
        ),
    ]
