# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0020_auto_20191207_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='type',
            field=models.CharField(choices=[('1', 'МО РФ'), ('2', 'МО РФ'), ('3', 'ГФС иное'), ('4', 'ГФС москва'), ('5', 'почта ФПС'), ('6', 'почта России'), ('7', 'посылки')], default='МО РФ', max_length=20, verbose_name='Тип реестра'),
        ),
    ]
