# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-07 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0023_auto_20191207_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
