# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0025_auto_20191207_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='registry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.RegistryType', verbose_name='Тип реестра'),
        ),
    ]
