# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-07 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0028_auto_20191207_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='rpo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.RPOType', verbose_name='Тип РПО'),
        ),
    ]
