# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0032_auto_20191209_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepient',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование адресата'),
        ),
    ]
