# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-10 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0034_remove_recepient_adds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenvelop',
            name='registry_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.RegistryType', verbose_name='Тип реестра'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentenvelop',
            name='envelop_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.Envelop', verbose_name='Формат конверта'),
        ),
        migrations.AlterField(
            model_name='sentenvelop',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.Recepient', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='sentenvelop',
            name='rpo_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.RPOType', verbose_name='Вид РПО'),
        ),
        migrations.AlterField(
            model_name='sentenvelop',
            name='secret_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.SecretType', verbose_name='Тип секретности'),
        ),
    ]
