# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-10 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepientsapp', '0035_auto_20191210_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenvelop',
            name='registry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepientsapp.Registry'),
        ),
    ]
